### PR TITLE
use the adal library for spn when --legacy is specified

### LINKED ISSUE #331: legacy flag does not work from version v0.0.30 when the login method is spn
How to reproduce it

kubelogin get-token --tenant-id <<tenant-id>> --server-id <<server-id>> --client-id <<client-id>> --client-secret <<client-secret>> --login spn --legacy

Expected outcome:

token with audience field has "spn:" prefix

It works fine  on version v0.0.29 and lower

### PR DESCRIPTION
**Pull request by weinong**
it will fix #331

### CODE REVIEW

File: pkg/token/serviceprincipaltoken_legacy.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+			return emptyToken, fmt.Errorf("failed to decode pkcs12 certificate while creating spt: %w", err)
+		}
+
+		spt, err = adal.NewServicePrincipalTokenFromCertificate(
+			p.oAuthConfig,
+			p.clientID,
+			cert,
+			rsaPrivateKey,
+			p.resourceID,
+			callback)
```
Comment (bcho) [inline pkg/token/serviceprincipaltoken_legacy.go:93]: https://pkg.go.dev/github.com/Azure/go-autorest/autorest/adal#NewServicePrincipalTokenFromCertificate

the callback here is optional, since it's using an empty implementation here, I think we can drop it?

File: pkg/token/serviceprincipaltoken_legacy.go [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+		err error
+	)
+
+	if p.clientSecret != "" {
+		spt, err = adal.NewServicePrincipalToken(
+			p.oAuthConfig,
+			p.clientID,
+			p.clientSecret,
+			p.resourceID,
+			callback)
```
Comment (bcho) [inline pkg/token/serviceprincipaltoken_legacy.go:71]: similar to comment in below

File: pkg/token/serviceprincipaltoken_legacy.go [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+			cert,
+			rsaPrivateKey,
+			p.resourceID,
+			callback)
+		if err != nil {
+			return emptyToken, fmt.Errorf("failed to create service principal token using cert: %s", err)
+		}
+	}
+
+	err = spt.Refresh()
```
Comment (bcho) [inline pkg/token/serviceprincipaltoken_legacy.go:99]: How about `EnsureFreshWithContext` so it can handle different kind of token expiry cases?

Comment (weinong) [reply pkg/token/serviceprincipaltoken_legacy.go:99]: this token provider doesn't cache, so it always gets fresh token

Comment (weinong) [reply pkg/token/serviceprincipaltoken_legacy.go:99]: but.. why not!

**Review by bcho — APPROVED** [review]
LGTM
